### ISSUE TITLE
show same information for CBS?

### ISSUE THREAD

**Issue by awfabian-rs** [oldarmyc/anchor#5]
Hi,

I'm not familiar with submitting github issues. This is a feature request. Hopefully, not misplaced.

Since CBS volumes (list with /details call, I believe) also have a storage node hash, it'd be nice to do almost exactly the same thing with CBS volumes as Anchor currently does with servers.

Thanks,
Adam F.

**Comment by oldarmyc** [comment]
Adam,

Working on this currently and will get it in as soon as I can.

Dave

**Comment by oldarmyc** [comment]
CBS host distribution has been added, and code deployed to the production site.

You can select CBS Hosts and get a similar breakdown as servers.
